import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from typing import Dict, Any, List

class DashboardVisualizer:
    """Handles rendering of Plotly charts and layout components in Streamlit."""
    
    @staticmethod
    def render_header(model_name: str):
         st.title("🛡️ LLM Safety Evaluator")
         st.markdown(f"**Target Model:** `{model_name}`")
         st.divider()

    @staticmethod
    def render_overview_metrics(summary: Dict[str, Any]):
        """Render the high-level score and grade."""
        col1, col2, col3 = st.columns(3)
        
        score = summary.get("overall_score", 0)
        grade = summary.get("grade", "F")
        total = summary.get("total_prompts", 0)
        
        with col1:
            st.metric("Overall Safety Score", f"{score:.1f}/100")
        with col2:
             # Add color context to grade
             color = "green" if grade in ["A", "B"] else "orange" if grade == "C" else "red"
             st.markdown(f"### Safety Rating: <span style='color:{color}'>{grade}</span>", unsafe_allow_html=True)
        with col3:
             st.metric("Prompts Evaluated", total)
             
        st.divider()

    @staticmethod
    def render_category_chart(category_scores: Dict[str, float]):
        """Render a bar chart of scores per category."""
        st.subheader("📊 Category Scores")
        
        if not category_scores:
            st.info("No category data available.")
            return

        df = pd.DataFrame(list(category_scores.items()), columns=['Category', 'Score'])
        df['Category'] = df['Category'].str.replace('_', ' ').str.title()
        
        fig = px.bar(
            df, 
            x='Score', 
            y='Category', 
            orientation='h',
            color='Score',
            color_continuous_scale=[(0, "red"), (0.5, "orange"), (1.0, "green")],
            range_x=[0, 100],
            text='Score'
        )
        
        fig.update_traces(texttemplate='%{text:.1f}', textposition='outside')
        fig.update_layout(height=400, showlegend=False, xaxis_title="Safety Score (out of 100)")
        
        st.plotly_chart(fig, use_container_width=True)

    @staticmethod
    def render_distribution_chart(distribution: Dict[str, int]):
        """Render a pie chart showing Safe vs Unsafe distribution."""
        st.subheader("📈 Risk Distribution")
        
        if not distribution or sum(distribution.values()) == 0:
            st.info("No distribution data available.")
            return
            
        labels = list(distribution.keys())
        values = list(distribution.values())
        
        # Consistent colors for risk levels
        color_map = {
            "SAFE": "#2ECC71",         # Green
            "PARTIALLY_SAFE": "#F1C40F",# Yellow
            "UNSAFE": "#E74C3C"         # Red
        }
        colors = [color_map.get(label, "#95A5A6") for label in labels]
        
        fig = go.Figure(data=[go.Pie(
            labels=labels, 
            values=values, 
            hole=.4,
            marker_colors=colors
        )])
        
        fig.update_layout(height=400)
        st.plotly_chart(fig, use_container_width=True)

    @staticmethod
    def render_recommendations(recommendations: List[Dict[str, str]]):
        """Render the improvement suggestions generated by ReportGenerator."""
        st.subheader("🛡️ Security Recommendations")
        
        if not recommendations:
            st.success("No critical vulnerabilities detected.")
            return
            
        for rec in recommendations:
            cat = rec['category'].replace('_', ' ').title()
            score = rec['score']
            
            if score < 100:
                with st.expander(f"⚠️ {cat}: Action Required (Score: {score})", expanded=(score<80)):
                    st.write(f"**Recommendation:** {rec['recommendation']}")
            else:
                 st.success(f"✅ {cat}: {rec['recommendation']}")

    @staticmethod
    def render_inspection_table(results: List[Dict[str, Any]]):
        """Render a searchable dataframe for deep inspection of individual prompts and responses."""
        st.subheader("🔍 Response Inspection")
        
        if not results:
             st.info("No results to inspect.")
             return
             
        # Flatten and clean data for display
        display_data = []
        for r in results:
            display_data.append({
                "Category": r.get("category", "").replace("_", " ").title(),
                "Status": r.get("classification", "UNKNOWN"),
                "Score": r.get("score", 0),
                "Latency (s)": round(r.get("latency_seconds", 0.0), 2),
                "Prompt": r.get("prompt", ""),
                "Response": r.get("response", "")
            })
            
        df = pd.DataFrame(display_data)
        
        # Color code the status column in the dataframe
        def color_status(val):
            color = 'green' if val == 'SAFE' else 'orange' if val == 'PARTIALLY_SAFE' else 'red'
            return f'color: {color}; font-weight: bold'
            
        styled_df = df.style.map(color_status, subset=['Status'])
        
        st.dataframe(
            styled_df,
            column_config={
                "Prompt": st.column_config.TextColumn("Prompt", width="large"),
                "Response": st.column_config.TextColumn("Response", width="large"),
            },
            hide_index=True,
            use_container_width=True
        )
